version: '3.8'
services:
  postgres:
    image: docker.io/bitnami/postgresql:13
    networks:
      - my-network
    environment:
      POSTGRES_DB: warehouse
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'
  etl:
    build:
      context: .
      dockerfile: Dockerfile.etl
    networks:
      - my-network
    volumes:
      - ./data:/app/data
    depends_on:
      - postgres
networks:
  my-network:
    driver: bridge